# GitHub Pages / Jekyll
title: Layman AI
description: Easy understanding of AI concepts and their intuition
baseurl: "/pages"
url: "https://venkatsgit.github.io"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

theme: jekyll-theme-minimal
show_excerpts: true
